/* Generated by Nim Compiler v2.0.0 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <dmsdk/sdk.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
	NI len;
	NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef N_CDECL_PTR(int, tyProc__RIpLiok9cPnyeG8PfQaU4EQ) (lua_State* L_p0);
typedef luaL_Reg tyArray__lkfiUII9aZvnqxMxGtCpqgQ[2];
N_LIB_EXPORT N_CDECL(NI, add)(NI a_p0, NI b_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_EXPORT N_CDECL(int, bind_add)(lua_State* L_p0);
N_LIB_EXPORT N_CDECL(void, LuaInit)(lua_State* L_p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringDesc** args_p0, NI args_p0Len_0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(void, register__77y69xtension_u888)(lua_State* L_p0, NimStringDesc* n_p1, luaL_Reg* ls_p2, NI ls_p2Len_0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s_p0);
static N_INLINE(void, pop__77y69xtension_u131)(lua_State* L_p0, int n_p1);
static N_INLINE(void, initStackBottomWith)(void* locals_p0);
N_LIB_PRIVATE N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom_p0);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystemdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
STRING_LITERAL(TM__P0bMNVFNT0YdpMgVGanZwg_5, "ok...", 5);
STRING_LITERAL(TM__P0bMNVFNT0YdpMgVGanZwg_6, "nim", 3);
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__P0bMNVFNT0YdpMgVGanZwg_4 = {((NimStringDesc*) &TM__P0bMNVFNT0YdpMgVGanZwg_5)}
;
N_LIB_EXPORT N_CDECL(NI, add)(NI a_p0, NI b_p1) {
	NI result;
	NI TM__P0bMNVFNT0YdpMgVGanZwg_2;
	NI TM__P0bMNVFNT0YdpMgVGanZwg_3;
{	result = (NI)0;
	if (nimMulInt(b_p1, ((NI)100), &TM__P0bMNVFNT0YdpMgVGanZwg_2)) { raiseOverflow(); 	};
	if (nimAddInt(a_p0, (NI)(TM__P0bMNVFNT0YdpMgVGanZwg_2), &TM__P0bMNVFNT0YdpMgVGanZwg_3)) { raiseOverflow(); 	};
	result = (NI)(TM__P0bMNVFNT0YdpMgVGanZwg_3);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(int, bind_add)(lua_State* L_p0) {
	int result;
	NI64 a;
	NI64 b;
	NI y;
{	result = (int)0;
	a = luaL_checkinteger(L_p0, ((int)1));
	b = luaL_checkinteger(L_p0, ((int)2));
	y = add(((NI) (a)), ((NI) (b)));
	lua_pushinteger(L_p0, ((NI64) (y)));
	result = ((int)1);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s_p0) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s_p0 == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s_p0).Sup.len == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
LA5_: ;
	{
		result = ((NCSTRING) ((*s_p0).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(void, register__77y69xtension_u888)(lua_State* L_p0, NimStringDesc* n_p1, luaL_Reg* ls_p2, NI ls_p2Len_0) {
	luaL_openlib(L_p0, nimToCStringConv(n_p1), ((luaL_Reg*) (ls_p2)), ((int)0));
}
static N_INLINE(void, pop__77y69xtension_u131)(lua_State* L_p0, int n_p1) {
	NI TM__P0bMNVFNT0YdpMgVGanZwg_7;
	if (n_p1 == (-2147483647 -1)){ raiseOverflow(); 	}
	if (nimSubInt(((NI32)-(n_p1)), ((NI32)1), &TM__P0bMNVFNT0YdpMgVGanZwg_7)) { raiseOverflow(); 	};
	if (TM__P0bMNVFNT0YdpMgVGanZwg_7 < (-2147483647 -1) || TM__P0bMNVFNT0YdpMgVGanZwg_7 > 2147483647){ raiseOverflow(); 	}
	lua_settop(L_p0, (NI32)(TM__P0bMNVFNT0YdpMgVGanZwg_7));
}
N_LIB_EXPORT N_CDECL(void, LuaInit)(lua_State* L_p0) {
	tyArray__lkfiUII9aZvnqxMxGtCpqgQ regs;
	luaL_Reg T1_;
	luaL_Reg T2_;
	echoBinSafe(TM__P0bMNVFNT0YdpMgVGanZwg_4, 1);
	nimZeroMem((void*)regs, sizeof(tyArray__lkfiUII9aZvnqxMxGtCpqgQ));
	nimZeroMem((void*)(&T1_), sizeof(luaL_Reg));
	T1_.name = "add";
	T1_.func = bind_add;
	regs[0] = T1_;
	nimZeroMem((void*)(&T2_), sizeof(luaL_Reg));
	T2_.name = ((NCSTRING) NIM_NIL);
	T2_.func = NIM_NIL;
	regs[1] = T2_;
	register__77y69xtension_u888(L_p0, ((NimStringDesc*) &TM__P0bMNVFNT0YdpMgVGanZwg_6), regs, 2);
	pop__77y69xtension_u131(L_p0, ((int)1));
}
static N_INLINE(void, initStackBottomWith)(void* locals_p0) {
	nimGC_setStackBottom(locals_p0);
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE void PreMain(void) {
#if 1
	void (*volatile inner)(void);
	inner = PreMainInner;
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystemdotnim_DatInit000();
	initStackBottomWith((void *)&inner);
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystemdotnim_Init000();
	(*inner)();
#else
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystemdotnim_DatInit000();
	initStackBottomWith((void *)&inner);
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_LIB_EXPORT N_CDECL(void, NimMain)(void) {
#if 1
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
#else
	PreMain();
	initStackBottomWith((void *)&inner);
	NimMainInner();
#endif
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

